In [1]:
from qutip import *

Matplotlib is building the font cache; this may take a moment.


In [3]:
import numpy as np

import matplotlib.pyplot as plt

In [5]:
print(Qobj())

Quantum object: dims=[[1], [1]], shape=(1, 1), type='scalar', dtype=Dense
Qobj data =
[[nan]]


In [6]:
#create a Qobj with a user defined data set by passing a list or array of data into the Qobj:
print(Qobj([[1],[2],[3],[4],[5]]))

Quantum object: dims=[[5], [1]], shape=(5, 1), type='ket', dtype=Dense
Qobj data =
[[1.]
 [2.]
 [3.]
 [4.]
 [5.]]


In [7]:
x = np.array([[1, 2, 3, 4, 5]])
print(Qobj(x))

Quantum object: dims=[[1], [5]], shape=(1, 5), type='bra', dtype=Dense
Qobj data =
[[1. 2. 3. 4. 5.]]


In [8]:
r = np.random.rand(4, 4)
print(Qobj(r))

Quantum object: dims=[[4], [4]], shape=(4, 4), type='oper', dtype=Dense, isherm=False
Qobj data =
[[0.74192799 0.51693149 0.4180531  0.35796805]
 [0.19847296 0.17397089 0.10427432 0.71273082]
 [0.23203016 0.23072568 0.74695307 0.81585501]
 [0.54561477 0.53969573 0.07618552 0.36275673]]


In [9]:
#Manipulating States and Operators
#create a Fock basis vacuum state vector with in a Hilbert space with 5 number states, from 0 to 4:
vac = basis(5, 0)

print(vac)

Quantum object: dims=[[5], [1]], shape=(5, 1), type='ket', dtype=Dense
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [10]:
# create a lowering operator corresponding to 5 number states using the destroy function:
a = destroy(5)

print(a)

Quantum object: dims=[[5], [5]], shape=(5, 5), type='oper', dtype=Dia, isherm=False
Qobj data =
[[0.         1.         0.         0.         0.        ]
 [0.         0.         1.41421356 0.         0.        ]
 [0.         0.         0.         1.73205081 0.        ]
 [0.         0.         0.         0.         2.        ]
 [0.         0.         0.         0.         0.        ]]


In [11]:
# apply the destruction operator to our vacuum state vac
print(a * vac)

Quantum object: dims=[[5], [1]], shape=(5, 1), type='ket', dtype=Dense
Qobj data =
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
